# Generated by Django 4.2.2 on 2023-07-21 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_rename_imgor_game_main_imgor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='main_screen',
            field=models.ImageField(default='games/unknown.png', upload_to='games/', verbose_name='скриншот'),
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 20, 44, 21, 517902), verbose_name='дата истечения'),
        ),
    ]
