# Generated by Django 4.2.2 on 2023-07-21 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_main_screen_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='main_screen',
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 21, 12, 1, 575234), verbose_name='дата истечения'),
        ),
    ]
