# Generated by Django 4.2.3 on 2023-07-25 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_game_main_screen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 19, 27, 22, 475708), verbose_name='дата истечения'),
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='скриншот')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_screens', to='games.game', verbose_name='игра')),
            ],
            options={
                'verbose_name': 'скриншот',
                'verbose_name_plural': 'скриншоты',
                'ordering': ('name',),
            },
        ),
    ]
