# Generated by Django 4.2.3 on 2023-07-25 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_invitecard_expiration_date_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 19, 44, 47, 174999), verbose_name='дата истечения'),
        ),
    ]
