# Generated by Django 4.2.3 on 2023-07-25 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_screen_screen_image_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 21, 4, 51, 348498), verbose_name='дата истечения'),
        ),
    ]
